import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class AddBooks extends javax.swing.JFrame {

    /**
     * Creates new form AddBooks
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public AddBooks() {
        super("Add Books");
        initComponents();
        conn = Databaseconnection.connetion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        isbnlabel = new javax.swing.JLabel();
        titlelable = new javax.swing.JLabel();
        authorlabel = new javax.swing.JLabel();
        publisherlabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        categorylabel = new javax.swing.JLabel();
        quantitylabel = new javax.swing.JLabel();
        textIsbn = new javax.swing.JTextField();
        textTitle = new javax.swing.JTextField();
        textAuthor = new javax.swing.JTextField();
        textPublisher = new javax.swing.JTextField();
        textDate = new javax.swing.JTextField();
        textCategory = new javax.swing.JTextField();
        textQuantity = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isbnlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        isbnlabel.setText("ISBN");
        jPanel2.add(isbnlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 50, 29));

        titlelable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlelable.setText("Title");
        jPanel2.add(titlelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 68, -1));

        authorlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        authorlabel.setText("Author");
        jPanel2.add(authorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        publisherlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        publisherlabel.setText("Publisher");
        jPanel2.add(publisherlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        datelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datelabel.setText("Date");
        jPanel2.add(datelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        categorylabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        categorylabel.setText("Category");
        jPanel2.add(categorylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        quantitylabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantitylabel.setText("Quantity");
        jPanel2.add(quantitylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        textIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIsbnActionPerformed(evt);
            }
        });
        jPanel2.add(textIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 180, 29));

        textTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTitleActionPerformed(evt);
            }
        });
        jPanel2.add(textTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 180, 30));
        jPanel2.add(textAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 180, 29));
        jPanel2.add(textPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 180, 31));

        textDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDateActionPerformed(evt);
            }
        });
        jPanel2.add(textDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 180, 31));
        jPanel2.add(textCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 180, 30));

        textQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantityActionPerformed(evt);
            }
        });
        jPanel2.add(textQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 180, 28));

        submitButton.setBackground(new java.awt.Color(153, 153, 153));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1111.jpg"))); // NOI18N
        submitButton.setText("  Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 180, 35));

        backButton.setBackground(new java.awt.Color(153, 153, 153));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-left-red-circle-web-glossy-icon-stock-illustration_gg64765226.jpg"))); // NOI18N
        backButton.setText("Back to Home");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home object = new Home();
        object.setVisible(true);
        
    }//GEN-LAST:event_backButtonActionPerformed

    private void textIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIsbnActionPerformed

    private void textTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTitleActionPerformed

    private void textDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDateActionPerformed

    private void textQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantityActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try{
            stmt = conn.createStatement();
            int Isbn = Integer.parseInt(textIsbn.getText());
            String title = textTitle.getText();
            String author = textAuthor.getText();
            String publisher = textPublisher.getText();
            String date = textDate.getText();
            String category = textCategory.getText();
            int quantity = Integer.parseInt(textQuantity.getText());
           
            String sql = "INSERT INTO books(ISBN,Title,Author,Publisher,Date,Category,Quantity)VALUES('"+Isbn+"', '"+title+"','"+author+"','"+publisher+"','"+date+"','"+category+"','"+quantity+"')";

            
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is sucessfuly inserted");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorlabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel categorylabel;
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel isbnlabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel publisherlabel;
    private javax.swing.JLabel quantitylabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField textAuthor;
    private javax.swing.JTextField textCategory;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textIsbn;
    private javax.swing.JTextField textPublisher;
    private javax.swing.JTextField textQuantity;
    private javax.swing.JTextField textTitle;
    private javax.swing.JLabel titlelable;
    // End of variables declaration//GEN-END:variables
}
