import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class AddMembers extends javax.swing.JFrame {

    /**
     * Creates new form AddMembers
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public AddMembers() {
        super ("Add_Members");
        initComponents();
        conn = Databaseconnection.connetion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Namefield = new javax.swing.JLabel();
        Emailfield = new javax.swing.JLabel();
        Cantactfield = new javax.swing.JLabel();
        Guradianfield = new javax.swing.JLabel();
        Idfield = new javax.swing.JLabel();
        Cityfield = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textId = new javax.swing.JTextField();
        textContact = new javax.swing.JTextField();
        textGuradian = new javax.swing.JTextField();
        textCity = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Backbutton = new javax.swing.JButton();
        Submitbutton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Namefield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Namefield.setText("Name");
        getContentPane().add(Namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 101, -1, -1));

        Emailfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Emailfield.setText("Email");
        getContentPane().add(Emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 169, -1, -1));

        Cantactfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cantactfield.setText("Contact No");
        getContentPane().add(Cantactfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 309, -1, -1));

        Guradianfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Guradianfield.setText("Guradian Name");
        getContentPane().add(Guradianfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 377, -1, -1));

        Idfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Idfield.setText("ID Number");
        getContentPane().add(Idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 240, -1, -1));

        Cityfield.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cityfield.setText("City");
        getContentPane().add(Cityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 446, -1, -1));

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });
        getContentPane().add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 97, 170, 29));
        getContentPane().add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 165, 170, 29));

        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });
        getContentPane().add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 235, 170, 31));
        getContentPane().add(textContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 304, 170, 30));
        getContentPane().add(textGuradian, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 373, 170, 29));
        getContentPane().add(textCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 441, 170, 31));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Add New Members", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        Backbutton.setBackground(new java.awt.Color(102, 102, 102));
        Backbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-left-red-circle-web-glossy-icon-stock-illustration_gg64765226.jpg"))); // NOI18N
        Backbutton.setText("Back to Home ");
        Backbutton.setBorder(null);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        Submitbutton.setBackground(new java.awt.Color(102, 102, 102));
        Submitbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit-icon-png-1.jpg"))); // NOI18N
        Submitbutton.setText("  Submit");
        Submitbutton.setBorder(null);
        Submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addComponent(Submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void SubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbuttonActionPerformed
        // TODO add your handling code here:
        try{
            stmt = conn.createStatement();
            String member_name = textName.getText();
            String email = textEmail.getText();
            String  Id_no = textId.getText();
            int contact_no = Integer.parseInt(textContact.getText());
            String Guardian_name = textGuradian.getText();
            String City = textCity.getText();
            
            String sql = "INSERT INTO NEW_MEMBER(Member_Name, Email,ID_Number,Contact_NO,Guardian_Name,City) VALUES('"+member_name+"', '"+email+"', '"+Id_no+"','"+contact_no+"','"+Guardian_name+"','"+City+"')";
            
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data is successfully inserted");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SubmitbuttonActionPerformed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:"
    }//GEN-LAST:event_textIdActionPerformed

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home object = new Home();
        object.setVisible(true);
        
          
    }//GEN-LAST:event_BackbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMembers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMembers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JLabel Cantactfield;
    private javax.swing.JLabel Cityfield;
    private javax.swing.JLabel Emailfield;
    private javax.swing.JLabel Guradianfield;
    private javax.swing.JLabel Idfield;
    private javax.swing.JLabel Namefield;
    private javax.swing.JButton Submitbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField textCity;
    private javax.swing.JTextField textContact;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textGuradian;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables
}
