
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class DeleteandUpadateBookDetails extends javax.swing.JFrame {

    /**
     * Creates new form DeleteStudentDetails
     */
    
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public DeleteandUpadateBookDetails() {
        initComponents();
        conn = Databaseconnectionprovider.connetion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        isbnlabel = new javax.swing.JLabel();
        titlelable = new javax.swing.JLabel();
        authorlabel = new javax.swing.JLabel();
        publisherlabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        categorylabel = new javax.swing.JLabel();
        quantitylabel = new javax.swing.JLabel();
        textIsbn = new javax.swing.JTextField();
        textTitle = new javax.swing.JTextField();
        textAuthor = new javax.swing.JTextField();
        textPublisher = new javax.swing.JTextField();
        textDate = new javax.swing.JTextField();
        textCategory = new javax.swing.JTextField();
        textQuantity = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        book = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete & Update Books Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isbnlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        isbnlabel.setText("ISBN");
        jPanel2.add(isbnlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 50, 29));

        titlelable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlelable.setText("Title");
        jPanel2.add(titlelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 68, -1));

        authorlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        authorlabel.setText("Author");
        jPanel2.add(authorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        publisherlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        publisherlabel.setText("Publisher");
        jPanel2.add(publisherlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        datelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datelabel.setText("Date");
        jPanel2.add(datelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        categorylabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        categorylabel.setText("Category");
        jPanel2.add(categorylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        quantitylabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantitylabel.setText("Quantity");
        jPanel2.add(quantitylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        textIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIsbnActionPerformed(evt);
            }
        });
        jPanel2.add(textIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 180, 29));

        textTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTitleActionPerformed(evt);
            }
        });
        jPanel2.add(textTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 180, 30));
        jPanel2.add(textAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 180, 29));
        jPanel2.add(textPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 180, 31));

        textDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDateActionPerformed(evt);
            }
        });
        jPanel2.add(textDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 180, 31));
        jPanel2.add(textCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 180, 30));

        textQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantityActionPerformed(evt);
            }
        });
        jPanel2.add(textQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 180, 28));

        deletebutton.setBackground(new java.awt.Color(153, 153, 153));
        deletebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        deletebutton.setText("  Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 180, 35));

        backButton.setBackground(new java.awt.Color(153, 153, 153));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-left-red-circle-web-glossy-icon-stock-illustration_gg64765226.jpg"))); // NOI18N
        backButton.setText("Back to Home");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 180, -1));

        update.setBackground(new java.awt.Color(153, 153, 153));
        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        update.setText("  Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 180, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Book ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));
        jPanel2.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 180, 30));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sss.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Delete Books Details");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIsbnActionPerformed

    private void textTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTitleActionPerformed

    private void textDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDateActionPerformed

    private void textQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantityActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        try{
            stmt = conn.createStatement();
            int bookid = Integer.parseInt(book.getText());
            String sql = "DELETE FROM books WHERE No = '"+bookid+"' ";
            stmt.executeUpdate(sql);
            
            setVisible(false);
            ShowAllDetails object = new ShowAllDetails();
            object.setVisible(true);
            
        }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
        
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home object = new Home();
        object.setVisible(true);

    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            try{
            stmt = conn.createStatement();
            int id = Integer.parseInt(book.getText());
        

            String sql = "SELECT * FROM books WHERE No = '"+id+"' ";
            
            rs = stmt.executeQuery(sql);
            
            if(rs.next()){
            
                textIsbn.setText(rs.getString("ISBN"));
                textTitle.setText(rs.getString("Title"));
                textAuthor.setText(rs.getString("Author"));
                textPublisher.setText(rs.getString("Publisher"));
                textDate.setText(rs.getString("Date"));
                textCategory.setText(rs.getString("Category"));
                textQuantity.setText(String.format("%s",rs.getInt("Quantity")));
            }else{
                JOptionPane.showMessageDialog(null," Details Not Found");
            }

            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is sucessfuly inserted");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
          try{
            stmt = conn.createStatement();      
            int bookid = Integer.parseInt(book.getText());
            int Isbn = Integer.parseInt(textIsbn.getText());
            String title = textTitle.getText();
            String author = textAuthor.getText();
            String publisher = textPublisher.getText();
            String date = textDate.getText();
            String category = textCategory.getText();
            int quantity = Integer.parseInt(textQuantity.getText());
           
            String sql = "UPDATE books SET ISBN='"+Isbn+"',Title='"+title+"',Author='"+author+"',Publisher='"+publisher+"',Date='"+date+"',Category='"+category+"',Quantity='"+quantity+"' ";

            
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is sucessfuly Updated");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteandUpadateBookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteandUpadateBookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteandUpadateBookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteandUpadateBookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteandUpadateBookDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorlabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField book;
    private javax.swing.JLabel categorylabel;
    private javax.swing.JLabel datelabel;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel isbnlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel publisherlabel;
    private javax.swing.JLabel quantitylabel;
    private javax.swing.JTextField textAuthor;
    private javax.swing.JTextField textCategory;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textIsbn;
    private javax.swing.JTextField textPublisher;
    private javax.swing.JTextField textQuantity;
    private javax.swing.JTextField textTitle;
    private javax.swing.JLabel titlelable;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
