
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class DeleteandUpdateMembersDetails extends javax.swing.JFrame {

    /**
     * Creates new form DeleteStudentsDetais
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    public DeleteandUpdateMembersDetails() {
        initComponents();
        conn = Databaseconnectionprovider.connetion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Backbutton = new javax.swing.JButton();
        Submitbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        member = new javax.swing.JTextField();
        textname = new javax.swing.JTextField();
        textemail = new javax.swing.JTextField();
        textnumber = new javax.swing.JTextField();
        textGuname = new javax.swing.JTextField();
        textcity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Delete & Update Members Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backbutton.setBackground(new java.awt.Color(102, 102, 102));
        Backbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-left-red-circle-web-glossy-icon-stock-illustration_gg64765226.jpg"))); // NOI18N
        Backbutton.setText("Back to Home ");
        Backbutton.setBorder(null);
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 169, 40));

        Submitbutton.setBackground(new java.awt.Color(102, 102, 102));
        Submitbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        Submitbutton.setText(" Update");
        Submitbutton.setActionCommand("  Update");
        Submitbutton.setBorder(null);
        Submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Submitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 169, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contact Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Guardian Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("City");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        jPanel1.add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 170, 30));

        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });
        jPanel1.add(textname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 170, 30));
        jPanel1.add(textemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 170, 30));
        jPanel1.add(textnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 170, 30));
        jPanel1.add(textGuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 170, 30));
        jPanel1.add(textcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 170, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 170, 40));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sss.png"))); // NOI18N
        jButton2.setText("  Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home object = new Home();
        object.setVisible(true);

    }//GEN-LAST:event_BackbuttonActionPerformed

    private void SubmitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbuttonActionPerformed
        // TODO add your handling code here:
          try{
            stmt = conn.createStatement();      
            int member_id = Integer.parseInt(member.getText());
            String name = textname.getText();
            String email = textemail.getText();
            String contact_no = textnumber.getText(); 
            String Guardian_name= textGuname.getText();
            String city = textcity.getText();
         
             
            String sql = "UPDATE new_member SET Member_Name ='"+name+"',Email='"+email+"',Contact_No='"+contact_no+"',Guardian_Name='"+Guardian_name+"',City='"+city+"' ";

            
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is sucessfuly Updated");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       
        
    }//GEN-LAST:event_SubmitbuttonActionPerformed

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnameActionPerformed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try{
              stmt = conn.createStatement();
              int member_id = Integer.parseInt(member.getText());
              String sql = "DELETE FROM new_member WHERE ID_Number='"+member_id+"' ";
              stmt.executeUpdate(sql);
              
              setVisible(false);
              ShowAllDetails object = new ShowAllDetails();
              object.setVisible(true);  
         
        }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            stmt = conn.createStatement();
            int id = Integer.parseInt(member.getText());
            
            String sql = "SELECT * FROM new_member WHERE ID_Number = '"+id+"' ";
            
            rs = stmt.executeQuery(sql);
            
            if(rs.next()){
            
                textname.setText(rs.getString("Member_Name"));
                textemail.setText(rs.getString("Email"));
                textnumber.setText(rs.getString("Contact_No"));
                textGuname.setText(rs.getString("Guardian_Name"));
                textcity.setText(rs.getString("City"));
              
            }else{
                JOptionPane.showMessageDialog(null," Details Not Found");
            }

            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is sucessfuly inserted");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteandUpdateMembersDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteandUpdateMembersDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteandUpdateMembersDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteandUpdateMembersDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteandUpdateMembersDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JButton Submitbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField member;
    private javax.swing.JTextField textGuname;
    private javax.swing.JTextField textcity;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textnumber;
    // End of variables declaration//GEN-END:variables
}
