/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class IssueBooks extends javax.swing.JFrame {

    /**
     * Creates new form IssueBooks
     */
    public IssueBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        Bookidlabel = new javax.swing.JLabel();
        MemberIdlabel = new javax.swing.JLabel();
        IssueDatelabel = new javax.swing.JLabel();
        Dueatelabel = new javax.swing.JLabel();
        IssueDate = new com.toedter.calendar.JDateChooser();
        DueDate = new com.toedter.calendar.JDateChooser();
        BokIdfield = new javax.swing.JTextField();
        MemberIdfield = new javax.swing.JTextField();
        IssueButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bookidlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bookidlabel.setText("Book ID");
        getContentPane().add(Bookidlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 173, 77, 23));

        MemberIdlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MemberIdlabel.setText("Member ID NO");
        getContentPane().add(MemberIdlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 230, -1, 23));

        IssueDatelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IssueDatelabel.setText("Issue Date");
        getContentPane().add(IssueDatelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 283, -1, -1));

        Dueatelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dueatelabel.setText("Due Date");
        getContentPane().add(Dueatelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 336, -1, -1));
        getContentPane().add(IssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 283, 183, 30));
        getContentPane().add(DueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 336, 183, 28));
        getContentPane().add(BokIdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 173, 183, 30));

        MemberIdfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberIdfieldActionPerformed(evt);
            }
        });
        getContentPane().add(MemberIdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 230, 183, 30));

        IssueButton.setBackground(new java.awt.Color(153, 153, 153));
        IssueButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IssueButton.setText("Isuue");
        IssueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IssueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 402, 183, 37));

        BackButton.setBackground(new java.awt.Color(153, 153, 153));
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-left-red-circle-web-glossy-icon-stock-illustration_gg64765226.jpg"))); // NOI18N
        BackButton.setText("  Back to Home");
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 468, 183, 40));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Issue Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MemberIdfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberIdfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberIdfieldActionPerformed

    private void IssueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_IssueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField BokIdfield;
    private javax.swing.JLabel Bookidlabel;
    private com.toedter.calendar.JDateChooser DueDate;
    private javax.swing.JLabel Dueatelabel;
    private javax.swing.JButton IssueButton;
    private com.toedter.calendar.JDateChooser IssueDate;
    private javax.swing.JLabel IssueDatelabel;
    private javax.swing.JTextField MemberIdfield;
    private javax.swing.JLabel MemberIdlabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
