import java.sql.Connection;
//import Project.Databaseconnection;
//import static java.awt.event.PaintEvent.UPDATE;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class ReturnBooks extends javax.swing.JFrame {

    //pivate Object con;

    /**
     * Creates new form ReturnBooks
     */
    //Connection conn = null;
    //Statement stmt = null;
    //ResultSet rs = null;
    
    public ReturnBooks() {
        initComponents();
      //  Connection conn = Databaseconnection.connetion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Booklabel = new javax.swing.JLabel();
        Memberlabel = new javax.swing.JLabel();
        Issuelabel = new javax.swing.JLabel();
        Duelabel = new javax.swing.JLabel();
        Bookfield = new javax.swing.JTextField();
        Memberfield = new javax.swing.JTextField();
        IssueField = new javax.swing.JTextField();
        DueField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Booklabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Booklabel.setText("Book ID");

        Memberlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Memberlabel.setText("Member ID");

        Issuelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Issuelabel.setText("Issue Date");

        Duelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Duelabel.setText("Due Date");

        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        ReturnButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ReturnButton.setText("Return");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setText("Back to Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Booklabel)
                    .addComponent(Memberlabel)
                    .addComponent(Issuelabel)
                    .addComponent(Duelabel))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ReturnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bookfield)
                        .addComponent(Memberfield)
                        .addComponent(IssueField)
                        .addComponent(DueField)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Booklabel)
                            .addComponent(Bookfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Memberlabel)
                            .addComponent(Memberfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IssueField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Issuelabel)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DueField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Duelabel))
                .addGap(32, 32, 32)
                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String bookID = Bookfield.getText();
        String memberID = Memberfield.getText();
        try{
            Connection con = Databaseconnection.getCon();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select *from issuebooks where No='"+bookID+"' and ID_Number='"+memberID+"'");
            if(rs.next())
            {
                IssueField.setText(rs.getString(3));
                DueField.setText(rs.getString(4));
                Bookfield.setEditable(false);
                Memberfield.setEditable(false);
                
            }
            else 
                JOptionPane.showMessageDialog(null,"Incorrect Member ID or Incorrect Book ID");
                setVisible(false);
                new ReturnBooks().setVisible(true);

        }
        catch(Exception e)
        {    
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
        
         
        String bookID = Bookfield.getText();
        String memberID = Memberfield.getText();
        try
        {
            Connection con=Databaseconnection.getCon();
            Statement st=con.createStatement();
            st.executeQuery("update issuebooks set ReturnBooks = 'YES' where ID_Number='"+memberID+"' and No='"+bookID+"')");
            JOptionPane.showMessageDialog(null,"Book successfully returned");
            setVisible(false);
            new ReturnBooks().setVisible(true);             
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"Connection Error");
            
        }
    }//GEN-LAST:event_ReturnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField Bookfield;
    private javax.swing.JLabel Booklabel;
    private javax.swing.JTextField DueField;
    private javax.swing.JLabel Duelabel;
    private javax.swing.JTextField IssueField;
    private javax.swing.JLabel Issuelabel;
    private javax.swing.JTextField Memberfield;
    private javax.swing.JLabel Memberlabel;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton SearchButton;
    // End of variables declaration//GEN-END:variables
}
